---
- name: SSH_Connection_Test
  hosts: all
  gather_facts: true
  roles:
    - connection_test
    - check_jmsfile
    - check_jms_status
    - unzip_jmsfile
    - replace_jmsfile
    - update_nginx
    - replace_jms_config

- name: JMS_Update
  hosts: all
  gather_facts: true
  roles:
    - { role: update_jumpserver , when: jms_runs.failed == false }
    - check_jms_status


#-----------暂时不需要------------
#- name: connection_test
#  hosts: all
#  tasks:
#    - import_role:
#        name: connection_test
