- name: 停止 Jumpserver 服务
  shell: cd {{JMS_WORKSPACE}} && ./jmsctl.sh stop
  register: jms_runs

- name: 更新 Nginx 配置文件
  template: 
    src: http_server.conf.j2
    dest: /tmp/http_server.conf
  when: Update_Nginx_Config == True